### ISSUE TITLE
CLAIR results on other datasets

### ISSUE THREAD

**Issue by Yebin46** [DavidMChan/clair#3]
Hello. Thank you for the interesting research. It is really impressive research that using LLM for image captioning evaluation.

If it's okay, could you also share the results for other datasets besides Flickr-Expert, such as COMPOSITE or PASCAL-50S?
I had tried to reproduce it myself like issue [#2](https://github.com/DavidMChan/clair/issues/2), but the result was not satisfactory. I would like to see the optimal results mentioned in the paper.

**Comment by DavidMChan** [comment]
Here are the results for the COMPOSITE dataset:
[palm-composite_correctness.json](https://github.com/DavidMChan/clair/files/13956547/palm-composite_correctness.json)
[claude-composite_correctness.json](https://github.com/DavidMChan/clair/files/13956546/claude-composite_correctness.json)
[gpt-composite_correctness.json](https://github.com/DavidMChan/clair/files/13956543/gpt-composite_correctness.json)

And the results on PASCAL:
[pascal_output_palm.json](https://github.com/DavidMChan/clair/files/13956557/pascal_output_palm.json)
[pascal_output_gpt.json](https://github.com/DavidMChan/clair/files/13956558/pascal_output_gpt.json)
[pascal_output_claude.json](https://github.com/DavidMChan/clair/files/13956560/pascal_output_claude.json)
